/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author faad2
 */
public class cadastroFornecedor extends javax.swing.JFrame {

    /**
     * Creates new form cadastroFornecedor
     */
    public cadastroFornecedor() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldCadNome = new javax.swing.JTextField();
        textFieldCadCNPJ = new javax.swing.JTextField();
        textFieldCadTel = new javax.swing.JTextField();
        textFieldCadEmail = new javax.swing.JTextField();
        labelCadFornecedor = new javax.swing.JLabel();
        buttonCadastrarFuncionario = new javax.swing.JButton();
        buttonCancelarCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(337, 287));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nome: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 35, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("CNPJ: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 35, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Telefone: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 48, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Email: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 140, 33, 14);

        textFieldCadNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadNomeActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldCadNome);
        textFieldCadNome.setBounds(70, 20, 190, 20);
        jPanel1.add(textFieldCadCNPJ);
        textFieldCadCNPJ.setBounds(70, 60, 190, 20);
        jPanel1.add(textFieldCadTel);
        textFieldCadTel.setBounds(70, 100, 190, 20);
        jPanel1.add(textFieldCadEmail);
        textFieldCadEmail.setBounds(70, 140, 190, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 30, 270, 180);

        labelCadFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelCadFornecedor.setText("Cadastrar Fornecedor");
        getContentPane().add(labelCadFornecedor);
        labelCadFornecedor.setBounds(40, 10, 140, 20);

        buttonCadastrarFuncionario.setText("Cadastrar");
        getContentPane().add(buttonCadastrarFuncionario);
        buttonCadastrarFuncionario.setBounds(70, 220, 100, 30);

        buttonCancelarCadastro.setText("Cancelar");
        getContentPane().add(buttonCancelarCadastro);
        buttonCancelarCadastro.setBounds(180, 220, 90, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCadNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadNomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroFornecedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarFuncionario;
    private javax.swing.JButton buttonCancelarCadastro;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelCadFornecedor;
    private javax.swing.JTextField textFieldCadCNPJ;
    private javax.swing.JTextField textFieldCadEmail;
    private javax.swing.JTextField textFieldCadNome;
    private javax.swing.JTextField textFieldCadTel;
    // End of variables declaration//GEN-END:variables
}
