package Visao;

public class cadastroVendas extends javax.swing.JFrame {

    public cadastroVendas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPainel = new javax.swing.JPanel();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelPainel1 = new javax.swing.JPanel();
        jLabelCPF1 = new javax.swing.JLabel();
        jPanelPainel2 = new javax.swing.JPanel();
        jLabelCPF2 = new javax.swing.JLabel();
        jTextFieldCPF3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelPainel3 = new javax.swing.JPanel();
        jLabelCPF3 = new javax.swing.JLabel();
        jTextFieldCPF4 = new javax.swing.JTextField();
        jPanelPainel4 = new javax.swing.JPanel();
        jLabelCPF4 = new javax.swing.JLabel();
        jTextFieldCPF5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelPainel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel.setLayout(null);

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF.setText("CPF:");
        jPanelPainel.add(jLabelCPF);
        jLabelCPF.setBounds(10, 10, 30, 14);

        jTextFieldCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF1ActionPerformed(evt);
            }
        });
        jPanelPainel.add(jTextFieldCPF1);
        jTextFieldCPF1.setBounds(50, 10, 160, 20);

        getContentPane().add(jPanelPainel);
        jPanelPainel.setBounds(27, 27, 230, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("IDENTIFICAR CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 4, 160, 20);

        jButtonCadastrar.setText("LOCALIZAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(270, 30, 100, 30);

        jLabel2.setText("NOME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 100, 70, 14);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(100, 100, 260, 20);

        jLabel4.setText("TELEFONE");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(394, 100, 60, 14);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 100, 140, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 150, 680, 250);

        jPanelPainel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel1.setLayout(null);

        jLabelCPF1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF1.setText("TOTAL");
        jPanelPainel1.add(jLabelCPF1);
        jLabelCPF1.setBounds(10, 10, 40, 15);

        jPanelPainel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel2.setLayout(null);

        jLabelCPF2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF2.setText("CÓDIGO DO PRODUTO");
        jPanelPainel2.add(jLabelCPF2);
        jLabelCPF2.setBounds(50, 10, 130, 15);

        jTextFieldCPF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF3ActionPerformed(evt);
            }
        });
        jPanelPainel2.add(jTextFieldCPF3);
        jTextFieldCPF3.setBounds(30, 30, 160, 20);

        jPanelPainel1.add(jPanelPainel2);
        jPanelPainel2.setBounds(20, 430, 230, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("R$ 199,99");
        jPanelPainel1.add(jLabel7);
        jLabel7.setBounds(20, 20, 90, 30);

        getContentPane().add(jPanelPainel1);
        jPanelPainel1.setBounds(290, 430, 140, 60);

        jButton1.setText("FINALIZAR");
        getContentPane().add(jButton1);
        jButton1.setBounds(590, 450, 100, 30);

        jButton2.setText("REGISTRAR");
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 450, 100, 30);

        jPanelPainel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel3.setLayout(null);

        jLabelCPF3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF3.setText("CÓDIGO DO PRODUTO");
        jPanelPainel3.add(jLabelCPF3);
        jLabelCPF3.setBounds(50, 10, 130, 15);

        jTextFieldCPF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF4ActionPerformed(evt);
            }
        });
        jPanelPainel3.add(jTextFieldCPF4);
        jTextFieldCPF4.setBounds(30, 30, 160, 20);

        jPanelPainel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel4.setLayout(null);

        jLabelCPF4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF4.setText("CÓDIGO DO PRODUTO");
        jPanelPainel4.add(jLabelCPF4);
        jLabelCPF4.setBounds(50, 10, 130, 15);

        jTextFieldCPF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF5ActionPerformed(evt);
            }
        });
        jPanelPainel4.add(jTextFieldCPF5);
        jTextFieldCPF5.setBounds(30, 30, 160, 20);

        jPanelPainel3.add(jPanelPainel4);
        jPanelPainel4.setBounds(20, 430, 230, 60);

        getContentPane().add(jPanelPainel3);
        jPanelPainel3.setBounds(20, 430, 230, 60);

        setBounds(0, 0, 746, 554);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed

    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF1ActionPerformed

    private void jTextFieldCPF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF3ActionPerformed

    private void jTextFieldCPF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF4ActionPerformed

    private void jTextFieldCPF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCPF1;
    private javax.swing.JLabel jLabelCPF2;
    private javax.swing.JLabel jLabelCPF3;
    private javax.swing.JLabel jLabelCPF4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelPainel;
    private javax.swing.JPanel jPanelPainel1;
    private javax.swing.JPanel jPanelPainel2;
    private javax.swing.JPanel jPanelPainel3;
    private javax.swing.JPanel jPanelPainel4;
    private javax.swing.JTextField jTextFieldCPF1;
    private javax.swing.JTextField jTextFieldCPF3;
    private javax.swing.JTextField jTextFieldCPF4;
    private javax.swing.JTextField jTextFieldCPF5;
    // End of variables declaration//GEN-END:variables
}
