/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControlEstoque;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFormattedTextField;

/**
 *
 * @author faad2
 */
public class CadastrarCarne extends javax.swing.JFrame {
    private String date1;
    private String date2;
    /**
     * Creates new form CadastrarCarne
     */
    public CadastrarCarne() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNomeCarne = new javax.swing.JTextField();
        jFormattedTextFieldDataVenci = new javax.swing.JFormattedTextField();
        jFormattedTextFieldQtdCarne = new javax.swing.JFormattedTextField();
        jFormattedTextFieldDataValid = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextFieldValor = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldMarca = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(375, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        jLabel1.setText("Nome: ");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(10, 20, 50, 14);

        jLabel2.setText("Data de Fabricação:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 130, 130, 14);

        jLabel3.setText("Data de vencimento: ");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 170, 120, 14);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bovina", "Suina", "Frango" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBoxTipo);
        jComboBoxTipo.setBounds(240, 20, 70, 20);

        jLabel4.setText("Tipo:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(210, 20, 34, 14);

        jLabel5.setText("Quantidade:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 80, 14);

        jLabel6.setText("KG");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(170, 60, 30, 14);

        jTextFieldNomeCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCarneActionPerformed(evt);
            }
        });
        jPanel2.add(jTextFieldNomeCarne);
        jTextFieldNomeCarne.setBounds(70, 20, 130, 20);

        jFormattedTextFieldDataVenci.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel2.add(jFormattedTextFieldDataVenci);
        jFormattedTextFieldDataVenci.setBounds(150, 170, 160, 20);

        jFormattedTextFieldQtdCarne.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel2.add(jFormattedTextFieldQtdCarne);
        jFormattedTextFieldQtdCarne.setBounds(80, 60, 80, 20);

        jFormattedTextFieldDataValid.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jPanel2.add(jFormattedTextFieldDataValid);
        jFormattedTextFieldDataValid.setBounds(150, 130, 160, 20);

        jLabel7.setText("Valor: ");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 90, 50, 20);

        jFormattedTextFieldValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jPanel2.add(jFormattedTextFieldValor);
        jFormattedTextFieldValor.setBounds(80, 90, 80, 20);

        jLabel8.setText("Marca:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(170, 90, 50, 20);
        jPanel2.add(jTextFieldMarca);
        jTextFieldMarca.setBounds(210, 90, 100, 20);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(30, 10, 320, 210);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 230, 110, 30);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(200, 230, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        date1 = jFormattedTextFieldDataValid.getText();
        date2 = jFormattedTextFieldDataVenci.getText();
        date1.replace("/", "-");
        date2.replace("/", "-");
        ControlEstoque.criarEstoque(jTextFieldNomeCarne.getText(), Double.parseDouble(jFormattedTextFieldValor.getText()), date1, date2, Double.parseDouble(jFormattedTextFieldQtdCarne.getText()), jComboBoxTipo.getSelectedItem().toString(), jTextFieldMarca.getText());
        jTextFieldNomeCarne.setText("");
        jFormattedTextFieldQtdCarne.setText("");
        jFormattedTextFieldDataValid.setText("");
        jFormattedTextFieldDataVenci.setText("");
        jTextFieldMarca.setText("");
        jFormattedTextFieldValor.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldNomeCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCarneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCarne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataValid;
    private javax.swing.JFormattedTextField jFormattedTextFieldDataVenci;
    private javax.swing.JFormattedTextField jFormattedTextFieldQtdCarne;
    private javax.swing.JFormattedTextField jFormattedTextFieldValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldMarca;
    private javax.swing.JTextField jTextFieldNomeCarne;
    // End of variables declaration//GEN-END:variables
}
