package Visao;

import ClassesDAO.ClienteDAO;
import Controle.ControlCarne;
import Controle.ControlItemPedido;
import Controle.ControlVenda;
import d.espetos.Carne;
import d.espetos.Cliente;
import d.espetos.ItemPedido;
import d.espetos.Venda;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;

public class CadastroVendas extends javax.swing.JFrame {
    private int linha;
    Carne[] vCarnes;
    private int codCliente;
    private double valor;
    private double valorTotal = 0.00;
    private int linhaAtual = 0;
    private double desconto;
    private java.sql.Date dataCompra;
    private java.sql.Date dataEntrega;
    List<ItemPedido> list = new ArrayList<>();
    public CadastroVendas() {
        initComponents();
        this.setLocationRelativeTo(null);
        jLabelPreco.setText("R$ " + ControlItemPedido.format(valorTotal));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        jTableItemsPedido.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        jTableItemsPedido.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        jTableCarnesDisponiveis.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        jTableCarnesDisponiveis.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPainel = new javax.swing.JPanel();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonCadastrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItemsPedido = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableCarnesDisponiveis = new javax.swing.JTable();
        jPanelPainel1 = new javax.swing.JPanel();
        jLabelCPF1 = new javax.swing.JLabel();
        jPanelPainel2 = new javax.swing.JPanel();
        jLabelCPF2 = new javax.swing.JLabel();
        jTextFieldCPF3 = new javax.swing.JTextField();
        jLabelPreco = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanelPainel3 = new javax.swing.JPanel();
        jLabelCPF3 = new javax.swing.JLabel();
        jTextFieldCodProduto = new javax.swing.JTextField();
        jPanelPainel4 = new javax.swing.JPanel();
        jLabelCPF4 = new javax.swing.JLabel();
        jTextFieldCPF5 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldQtd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldDesconto = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFielddataCompra = new javax.swing.JFormattedTextField();
        jTextFieldDataEntrega = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanelPainel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel.setLayout(null);

        jLabelCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF.setText("CPF:");
        jPanelPainel.add(jLabelCPF);
        jLabelCPF.setBounds(10, 10, 30, 14);

        jTextFieldCPF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF1ActionPerformed(evt);
            }
        });
        jPanelPainel.add(jTextFieldCPF1);
        jTextFieldCPF1.setBounds(50, 10, 160, 20);

        getContentPane().add(jPanelPainel);
        jPanelPainel.setBounds(27, 27, 230, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("IDENTIFICAR CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 4, 160, 20);

        jButtonCadastrar.setText("LOCALIZAR");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrar);
        jButtonCadastrar.setBounds(270, 30, 100, 30);

        jLabel2.setText("NOME CLIENTE");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 70, 100, 14);
        getContentPane().add(jLabelNome);
        jLabelNome.setBounds(120, 70, 240, 20);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTableItemsPedido.setModel(new ItemPedidoTableModel());
        jScrollPane1.setViewportView(jTableItemsPedido);

        jTableCarnesDisponiveis.setModel(new CarnesDisponiveisTableModel(ControlCarne.getListOfCarnesView()));
        jTableCarnesDisponiveis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCarnesDisponiveisMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableCarnesDisponiveis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 90, 880, 380);

        jPanelPainel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel1.setLayout(null);

        jLabelCPF1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF1.setText("TOTAL");
        jPanelPainel1.add(jLabelCPF1);
        jLabelCPF1.setBounds(10, 10, 40, 15);

        jPanelPainel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel2.setLayout(null);

        jLabelCPF2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF2.setText("CÓDIGO DO PRODUTO");
        jPanelPainel2.add(jLabelCPF2);
        jLabelCPF2.setBounds(50, 10, 130, 15);

        jTextFieldCPF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF3ActionPerformed(evt);
            }
        });
        jPanelPainel2.add(jTextFieldCPF3);
        jTextFieldCPF3.setBounds(30, 30, 160, 20);

        jPanelPainel1.add(jPanelPainel2);
        jPanelPainel2.setBounds(20, 430, 230, 60);

        jLabelPreco.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPreco.setText("R$ 00,00");
        jPanelPainel1.add(jLabelPreco);
        jLabelPreco.setBounds(30, 20, 140, 30);

        getContentPane().add(jPanelPainel1);
        jPanelPainel1.setBounds(310, 540, 190, 60);

        jButton1.setText("FINALIZAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(780, 540, 110, 50);

        jButton2.setText("ADICIONAR À COMPRA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(460, 480, 190, 40);

        jPanelPainel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel3.setLayout(null);

        jLabelCPF3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF3.setText("CÓDIGO DO PRODUTO");
        jPanelPainel3.add(jLabelCPF3);
        jLabelCPF3.setBounds(10, 10, 130, 15);

        jTextFieldCodProduto.setEditable(false);
        jTextFieldCodProduto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCodProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCodProdutoActionPerformed(evt);
            }
        });
        jPanelPainel3.add(jTextFieldCodProduto);
        jTextFieldCodProduto.setBounds(40, 30, 70, 20);

        jPanelPainel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelPainel4.setLayout(null);

        jLabelCPF4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelCPF4.setText("CÓDIGO DO PRODUTO");
        jPanelPainel4.add(jLabelCPF4);
        jLabelCPF4.setBounds(50, 10, 130, 15);

        jTextFieldCPF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCPF5ActionPerformed(evt);
            }
        });
        jPanelPainel4.add(jTextFieldCPF5);
        jTextFieldCPF5.setBounds(30, 30, 160, 20);

        jPanelPainel3.add(jPanelPainel4);
        jPanelPainel4.setBounds(20, 430, 230, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("QUANTIDADE");
        jPanelPainel3.add(jLabel3);
        jLabel3.setBounds(160, 10, 90, 15);

        jTextFieldQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldQtdActionPerformed(evt);
            }
        });
        jPanelPainel3.add(jTextFieldQtd);
        jTextFieldQtd.setBounds(160, 30, 60, 20);

        jLabel4.setText("KG");
        jPanelPainel3.add(jLabel4);
        jLabel4.setBounds(230, 30, 30, 20);

        getContentPane().add(jPanelPainel3);
        jPanelPainel3.setBounds(30, 540, 260, 60);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("DESCONTO");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("R$");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(510, 540, 110, 60);

        jTextFielddataCompra.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Compra"));
        jTextFielddataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        jTextFielddataCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddataCompraActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFielddataCompra);
        jTextFielddataCompra.setBounds(660, 520, 110, 40);

        jTextFieldDataEntrega.setBorder(javax.swing.BorderFactory.createTitledBorder("Data de Entrega"));
        jTextFieldDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));
        getContentPane().add(jTextFieldDataEntrega);
        jTextFieldDataEntrega.setBounds(660, 570, 110, 40);

        setBounds(0, 0, 930, 657);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        List<Cliente> vList = ClienteDAO.getInstance().retrieveLikeCpf(jTextFieldCPF1.getText());
        jLabelNome.setText(vList.get(0).getNomeCliente());
        codCliente = vList.get(0).getIdCliente();
    }//GEN-LAST:event_jButtonCadastrarActionPerformed

    private void jTextFieldCPF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF1ActionPerformed

    private void jTextFieldCPF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF3ActionPerformed

    private void jTextFieldCodProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCodProdutoActionPerformed
        linha = jTableCarnesDisponiveis.getSelectedRow();
        jTextFieldCodProduto.setText(jTableCarnesDisponiveis.getValueAt(linha, 0).toString());
    }//GEN-LAST:event_jTextFieldCodProdutoActionPerformed

    private void jTextFieldCPF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCPF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCPF5ActionPerformed

    private void jTextFieldQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldQtdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldQtdActionPerformed

    private void jTableCarnesDisponiveisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCarnesDisponiveisMouseClicked
        linha = jTableCarnesDisponiveis.getSelectedRow();
        jTextFieldCodProduto.setText(jTableCarnesDisponiveis.getValueAt(linha, 0).toString());        
    }//GEN-LAST:event_jTableCarnesDisponiveisMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        linha = jTableCarnesDisponiveis.getSelectedRow();
        Carne c = (Carne) ((CarnesDisponiveisTableModel) jTableCarnesDisponiveis.getModel()).getItem(linha);
        Cliente cliente = new Cliente();
        cliente.setIdCliente(codCliente);
        valor = c.getValorCusto() * Double.parseDouble(jTextFieldQtd.getText());
        ItemPedido itemPed = new ItemPedido(cliente, (ArrayList<ItemPedido>) list, c, Double.parseDouble(jTextFieldQtd.getText().toString()), valor);
        list.add(itemPed);
        ((ItemPedidoTableModel) jTableItemsPedido.getModel()).addRow(itemPed);
        valorTotal += Double.parseDouble(jTableItemsPedido.getValueAt(linhaAtual, 2).toString().replace(",", "."));
        jLabelPreco.setText("R$ " + ControlItemPedido.format(valorTotal));
        linhaAtual++;
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(int i = 0; i < list.size(); i++){
            System.out.println("Item: " + i+1);
            System.out.println("Codigo do cliente: " + list.get(i).getCliente().getIdCliente());
            System.out.println("Codigo tipo da carne: " + list.get(i).getC().getCodTipo());
            System.out.println("Valor do item: " + list.get(i).getValorVenda());
            System.out.println("Quantidade do item pedido: " + list.get(i).getQuantidade());
        }
        desconto = Double.parseDouble(jTextFieldDesconto.getText());
        Venda v = new Venda();
        Cliente c = new Cliente();
        c.setIdCliente(codCliente);
        v.setDataCompra(dataCompra);
        v.setDataEntrega(dataEntrega);
        v.setDesconto(desconto);
        v.setValor(valorTotal - v.getDesconto());
        v.setCliente(c);
        ControlVenda.criarVenda(codCliente, jTextFielddataCompra.getText().replace("/","-"), jTextFieldDataEntrega.getText().replace("/","-"), desconto);
        FormaDePagamento formaPag = new FormaDePagamento(this, true, v, list);
        formaPag.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFielddataCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddataCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddataCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroVendas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCPF1;
    private javax.swing.JLabel jLabelCPF2;
    private javax.swing.JLabel jLabelCPF3;
    private javax.swing.JLabel jLabelCPF4;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelPainel;
    private javax.swing.JPanel jPanelPainel1;
    private javax.swing.JPanel jPanelPainel2;
    private javax.swing.JPanel jPanelPainel3;
    private javax.swing.JPanel jPanelPainel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableCarnesDisponiveis;
    private javax.swing.JTable jTableItemsPedido;
    private javax.swing.JTextField jTextFieldCPF1;
    private javax.swing.JTextField jTextFieldCPF3;
    private javax.swing.JTextField jTextFieldCPF5;
    private javax.swing.JTextField jTextFieldCodProduto;
    private javax.swing.JFormattedTextField jTextFieldDataEntrega;
    private javax.swing.JTextField jTextFieldDesconto;
    private javax.swing.JTextField jTextFieldQtd;
    private javax.swing.JFormattedTextField jTextFielddataCompra;
    // End of variables declaration//GEN-END:variables
}
