/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author faad2
 */
public class CadastrarCarne extends javax.swing.JFrame {

    /**
     * Creates new form CadastrarCarne
     */
    public CadastrarCarne() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxTipoCarne = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TextFieldNomeCarne = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TextFieldDiaValidade = new javax.swing.JTextField();
        jTextFieldMesValidade = new javax.swing.JTextField();
        jTextFieldAnoValidade = new javax.swing.JTextField();
        jTextFieldAnoFabricacao = new javax.swing.JTextField();
        jTextFieldDiaFabricacao = new javax.swing.JTextField();
        jTextFieldMesFabricacao = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 300));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Quantidade: ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 85, -1, -1));

        jLabel2.setText("Data de Fabricação");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 178, -1, -1));

        jLabel3.setText("Data de Validade");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 128, -1, -1));

        ComboBoxTipoCarne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ComboBoxTipoCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxTipoCarneActionPerformed(evt);
            }
        });
        jPanel1.add(ComboBoxTipoCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 90, 21));

        jLabel4.setText("Tipo:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 32, -1));

        jLabel5.setText("Nome: ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 42, -1, -1));
        jPanel1.add(TextFieldNomeCarne, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 39, 123, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(97, 82, 63, -1));

        jLabel6.setText("KG");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 85, -1, -1));
        jPanel1.add(TextFieldDiaValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 125, 23, -1));
        jPanel1.add(jTextFieldMesValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 125, 24, -1));
        jPanel1.add(jTextFieldAnoValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 125, 42, -1));
        jPanel1.add(jTextFieldAnoFabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 175, 39, -1));
        jPanel1.add(jTextFieldDiaFabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 175, 23, -1));
        jPanel1.add(jTextFieldMesFabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(162, 175, 24, -1));

        jLabel7.setText("/");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 128, -1, -1));

        jLabel8.setText("/");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(178, 128, -1, -1));

        jLabel9.setText("/");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 178, -1, -1));

        jLabel10.setText("/");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 178, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(30, 496, 376, 249);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComboBoxTipoCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxTipoCarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxTipoCarneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarCarne.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastrarCarne().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxTipoCarne;
    private javax.swing.JTextField TextFieldDiaValidade;
    private javax.swing.JTextField TextFieldNomeCarne;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldAnoFabricacao;
    private javax.swing.JTextField jTextFieldAnoValidade;
    private javax.swing.JTextField jTextFieldDiaFabricacao;
    private javax.swing.JTextField jTextFieldMesFabricacao;
    private javax.swing.JTextField jTextFieldMesValidade;
    // End of variables declaration//GEN-END:variables
}
