/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControlFornecedor;
import javax.swing.JOptionPane;

/**
 *
 * @author rafae
 */
public class CadFornecedorDialog extends javax.swing.JDialog {

    /**
     * Creates new form CadFornecedorDialog
     */
    public CadFornecedorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldCadNome = new javax.swing.JTextField();
        textFieldCadCNPJ = new javax.swing.JTextField();
        textFieldCadTel = new javax.swing.JTextField();
        textFieldCadEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldRuaFor = new javax.swing.JTextField();
        jTextFieldNumFor = new javax.swing.JTextField();
        jTextFieldCidFor = new javax.swing.JTextField();
        jTextFieldUfFor = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldBairroFor = new javax.swing.JTextField();
        labelCadFornecedor = new javax.swing.JLabel();
        buttonCadastrarFuncionario = new javax.swing.JButton();
        buttonCancelarCadastro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel2.setText("Nome: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(20, 20, 35, 14);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel3.setText("CNPJ: ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 60, 35, 14);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel4.setText("Telefone: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 100, 48, 14);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel5.setText("Email: ");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 33, 14);

        textFieldCadNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadNomeActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldCadNome);
        textFieldCadNome.setBounds(70, 20, 240, 22);
        jPanel1.add(textFieldCadCNPJ);
        textFieldCadCNPJ.setBounds(70, 60, 240, 22);
        jPanel1.add(textFieldCadTel);
        textFieldCadTel.setBounds(70, 100, 240, 22);

        textFieldCadEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCadEmailActionPerformed(evt);
            }
        });
        jPanel1.add(textFieldCadEmail);
        textFieldCadEmail.setBounds(70, 240, 240, 22);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel1.setText("Rua:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 140, 22, 14);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel6.setText("Cidade:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 200, 40, 20);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel7.setText("Número:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(230, 130, 60, 40);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel8.setText("UF:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(240, 200, 50, 20);
        jPanel1.add(jTextFieldRuaFor);
        jTextFieldRuaFor.setBounds(70, 140, 150, 22);
        jPanel1.add(jTextFieldNumFor);
        jTextFieldNumFor.setBounds(280, 140, 30, 22);
        jPanel1.add(jTextFieldCidFor);
        jTextFieldCidFor.setBounds(70, 200, 150, 22);
        jPanel1.add(jTextFieldUfFor);
        jTextFieldUfFor.setBounds(270, 200, 40, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        jLabel9.setText("Bairro: ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(20, 170, 40, 14);
        jPanel1.add(jTextFieldBairroFor);
        jTextFieldBairroFor.setBounds(70, 170, 230, 22);

        labelCadFornecedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        labelCadFornecedor.setText("Cadastrar Fornecedor");

        buttonCadastrarFuncionario.setText("Cadastrar");
        buttonCadastrarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastrarFuncionarioActionPerformed(evt);
            }
        });

        buttonCancelarCadastro.setText("Cancelar");
        buttonCancelarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarCadastroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(buttonCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(buttonCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(labelCadFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonCadastrarFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancelarCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCadNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadNomeActionPerformed

    private void textFieldCadEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCadEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCadEmailActionPerformed

    private void buttonCadastrarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastrarFuncionarioActionPerformed
        if(textFieldCadNome.getText().length() == 0 || textFieldCadCNPJ.getText().length() == 0 || textFieldCadEmail.getText().length() == 0 || textFieldCadTel.getText().length() == 0 || jTextFieldBairroFor.getText().length() == 0 || jTextFieldCidFor.getText().length() == 0 || jTextFieldNumFor.getText().length() == 0 || jTextFieldNumFor.getText().length() == 0 || jTextFieldRuaFor.getText().length() == 0 || jTextFieldUfFor.getText().length() == 0){
            JOptionPane.showMessageDialog(null, "Todos os dados devem ser preenchidos");
        }
        else{
            ControlFornecedor.criarFornecedor(textFieldCadNome.getText(), textFieldCadTel.getText(), textFieldCadCNPJ.getText(), textFieldCadEmail.getText(), jTextFieldRuaFor.getText(), jTextFieldNumFor.getText(), jTextFieldBairroFor.getText(), jTextFieldCidFor.getText(), jTextFieldUfFor.getText());
            textFieldCadTel.setText("");
            textFieldCadCNPJ.setText("");
            textFieldCadNome.setText("");
            textFieldCadEmail.setText("");
            jTextFieldBairroFor.setText("");
            jTextFieldCidFor.setText("");
            jTextFieldNumFor.setText("");
            jTextFieldRuaFor.setText("");
            jTextFieldUfFor.setText("");    
        } 
    }//GEN-LAST:event_buttonCadastrarFuncionarioActionPerformed

    private void buttonCancelarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarCadastroActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarCadastroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadFornecedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadFornecedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadFornecedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadFornecedorDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadFornecedorDialog dialog = new CadFornecedorDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadastrarFuncionario;
    private javax.swing.JButton buttonCancelarCadastro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldBairroFor;
    private javax.swing.JTextField jTextFieldCidFor;
    private javax.swing.JTextField jTextFieldNumFor;
    private javax.swing.JTextField jTextFieldRuaFor;
    private javax.swing.JTextField jTextFieldUfFor;
    private javax.swing.JLabel labelCadFornecedor;
    private javax.swing.JTextField textFieldCadCNPJ;
    private javax.swing.JTextField textFieldCadEmail;
    private javax.swing.JTextField textFieldCadNome;
    private javax.swing.JTextField textFieldCadTel;
    // End of variables declaration//GEN-END:variables
}
