/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author faad2
 */
public class listClientes extends javax.swing.JFrame {

    /**
     * Creates new form listClientes
     */
    public listClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTituloBusca = new javax.swing.JLabel();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        tableListarCliente = new javax.swing.JTable();
        textFieldBuscaNome = new javax.swing.JTextField();
        jLabelBuscaNome = new javax.swing.JLabel();
        jLabelBuscaCPF = new javax.swing.JLabel();
        jTextFieldBuscaCPF = new javax.swing.JTextField();
        jButtonBuscarCliente = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        labelTituloBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTituloBusca.setText("Busca de Clientes");
        jPanel1.add(labelTituloBusca);
        labelTituloBusca.setBounds(300, 0, 110, 20);

        tableListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "E-mail"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPaneClientes.setViewportView(tableListarCliente);

        jPanel1.add(jScrollPaneClientes);
        jScrollPaneClientes.setBounds(20, 70, 700, 360);
        jPanel1.add(textFieldBuscaNome);
        textFieldBuscaNome.setBounds(120, 30, 220, 20);

        jLabelBuscaNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBuscaNome.setText("Buscar por Nome ");
        jPanel1.add(jLabelBuscaNome);
        jLabelBuscaNome.setBounds(20, 30, 100, 15);

        jLabelBuscaCPF.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBuscaCPF.setText("Buscar por CPF");
        jPanel1.add(jLabelBuscaCPF);
        jLabelBuscaCPF.setBounds(370, 30, 90, 14);
        jPanel1.add(jTextFieldBuscaCPF);
        jTextFieldBuscaCPF.setBounds(470, 30, 150, 20);

        jButtonBuscarCliente.setText("Buscar");
        jPanel1.add(jButtonBuscarCliente);
        jButtonBuscarCliente.setBounds(640, 30, 73, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 740, 440);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoTodos.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(-20, -20, 830, 520);

        setBounds(0, 0, 806, 512);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBuscaCPF;
    private javax.swing.JLabel jLabelBuscaNome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JTextField jTextFieldBuscaCPF;
    private javax.swing.JLabel labelTituloBusca;
    private javax.swing.JTable tableListarCliente;
    private javax.swing.JTextField textFieldBuscaNome;
    // End of variables declaration//GEN-END:variables
}
