/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import ClassesDAO.ClienteDAO;
import Controle.ControlCliente;
import d.espetos.Cliente;
import javax.swing.JOptionPane;

/**
 *
 * @author faad2
 */
public class ListClientes extends javax.swing.JFrame {

    /**
     * Creates new form listClientes
     */
    Cliente[] vContatos;
    
    public ListClientes() {
        initComponents();
        this.setLocationRelativeTo(null);
        vContatos = ControlCliente.getListOfClientesAsArray();
        tableListarCliente.getColumnModel().getColumn(0).setPreferredWidth(30);
        ((ClienteTableModel) tableListarCliente.getModel()).refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTituloBusca = new javax.swing.JLabel();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        tableListarCliente = new javax.swing.JTable();
        textFieldBuscaNome = new javax.swing.JTextField();
        jLabelBuscaNome = new javax.swing.JLabel();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButtonEditCliente = new javax.swing.JButton();
        jButtonCadCliente = new javax.swing.JButton();
        jButtonRemoveCliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuItemCadastroCliente = new javax.swing.JMenuItem();
        menuItemListarClientes = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuItemListarEstoque = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuItemRelatorioVenda = new javax.swing.JMenuItem();
        menuItemRealizarVenda = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(830, 520));
        jPanel1.setLayout(null);

        labelTituloBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTituloBusca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloBusca.setText("CLIENTES");
        jPanel1.add(labelTituloBusca);
        labelTituloBusca.setBounds(300, 0, 110, 20);

        tableListarCliente.setModel(new ClienteTableModel(ControlCliente.getListOfClientes()));
        tableListarCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListarClienteMouseClicked(evt);
            }
        });
        jScrollPaneClientes.setViewportView(tableListarCliente);

        jPanel1.add(jScrollPaneClientes);
        jScrollPaneClientes.setBounds(20, 70, 710, 290);
        jPanel1.add(textFieldBuscaNome);
        textFieldBuscaNome.setBounds(120, 30, 400, 20);

        jLabelBuscaNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBuscaNome.setText("Buscar por Nome ");
        jPanel1.add(jLabelBuscaNome);
        jLabelBuscaNome.setBounds(20, 30, 100, 15);

        jButtonBuscarCliente.setText("Buscar");
        jButtonBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonBuscarCliente);
        jButtonBuscarCliente.setBounds(530, 30, 90, 23);

        jButtonEditCliente.setText("Editar");
        jButtonEditCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditCliente);
        jButtonEditCliente.setBounds(280, 380, 160, 40);

        jButtonCadCliente.setText("Cadastrar");
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadCliente);
        jButtonCadCliente.setBounds(80, 380, 160, 40);

        jButtonRemoveCliente.setText("Remover");
        jButtonRemoveCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveClienteActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemoveCliente);
        jButtonRemoveCliente.setBounds(470, 380, 160, 40);

        jButton1.setText("Atualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(630, 30, 100, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 750, 440);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoTodos.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(-20, -20, 830, 520);

        menuPrincipal.setText("Menu Principal");
        menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Menu Principal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuPrincipal.add(jMenuItem3);

        barraMenu.add(menuPrincipal);

        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });

        menuItemCadastroCliente.setText("Cadastrar Cliente");
        menuItemCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemCadastroCliente);

        menuItemListarClientes.setText("Listar Clientes");
        menuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemListarClientes);

        barraMenu.add(menuClientes);

        jMenuFornecedores.setText("Fornecedores");

        jMenuItem1.setText("Cadastrar Fornecedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuItem1);

        jMenuItem2.setText("Listar Fornecedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuItem2);

        barraMenu.add(jMenuFornecedores);

        menuEstoque.setText("Estoque");

        menuItemListarEstoque.setText("Listar Carnes");
        menuItemListarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemListarEstoque);

        barraMenu.add(menuEstoque);

        menuVendas.setText("Vendas");

        menuItemRelatorioVenda.setText("Relatório de Vendas");
        menuItemRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuItemRelatorioVenda);

        menuItemRealizarVenda.setText("Realizar Venda");
        menuItemRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRealizarVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuItemRealizarVenda);

        barraMenu.add(menuVendas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        barraMenu.add(jMenuSair);

        setJMenuBar(barraMenu);

        setBounds(0, 0, 806, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEditClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditClienteActionPerformed
        int linhaSelecionada = tableListarCliente.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Escolha um cliente!");
        }
        else{
            //Cliente cliente = new Cliente((Integer) tableListarCliente.getValueAt(linhaSelecionada, 0), tableListarCliente.getValueAt(linhaSelecionada, 1).toString(),tableListarCliente.getValueAt(linhaSelecionada, 4).toString(),tableListarCliente.getValueAt(linhaSelecionada, 3).toString(),tableListarCliente.getValueAt(linhaSelecionada, 5).toString(), tableListarCliente.getValueAt(linhaSelecionada, 2).toString());
            Cliente cliente = (Cliente) ((ClienteTableModel) tableListarCliente.getModel()).getItem(linhaSelecionada);
            EditarCliente editCliente = new EditarCliente(cliente);
            editCliente.setVisible(true);
        }
    }//GEN-LAST:event_jButtonEditClienteActionPerformed

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        cadastroClientes cadCliente = new cadastroClientes();
        cadCliente.setVisible(true);
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonRemoveClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveClienteActionPerformed
        int linhaSelecionada = tableListarCliente.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Escolha um cliente!");
        }
        else{
            Cliente cliente = new Cliente((Integer) tableListarCliente.getValueAt(linhaSelecionada, 0), tableListarCliente.getValueAt(linhaSelecionada, 1).toString(),tableListarCliente.getValueAt(linhaSelecionada, 4).toString(),tableListarCliente.getValueAt(linhaSelecionada, 3).toString(),tableListarCliente.getValueAt(linhaSelecionada, 5).toString(), tableListarCliente.getValueAt(linhaSelecionada, 2).toString());
            ClienteDAO.getInstance().delete(cliente);
            ((ClienteTableModel) tableListarCliente.getModel()).refresh();
        }
    }//GEN-LAST:event_jButtonRemoveClienteActionPerformed

    private void tableListarClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListarClienteMouseClicked
        int linha = tableListarCliente.getSelectedRow();
        Cliente c = (Cliente) ((ClienteTableModel) tableListarCliente.getModel()).getItem(linha);
    }//GEN-LAST:event_tableListarClienteMouseClicked

    private void jButtonBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarClienteActionPerformed
        ControlCliente.getListOfClientesNome(textFieldBuscaNome.getText());
        ((ClienteTableModel) tableListarCliente.getModel()).refresh();
    }//GEN-LAST:event_jButtonBuscarClienteActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MenuInicial principal = new MenuInicial();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalActionPerformed
        MenuInicial principal = new MenuInicial();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuPrincipalActionPerformed

    private void menuItemCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroClienteActionPerformed
        cadastroClientes clientes = new cadastroClientes();
        clientes.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroClienteActionPerformed

    private void menuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarClientesActionPerformed
        ListClientes cliente = new ListClientes();
        cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemListarClientesActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        cadastroClientes clientes = new cadastroClientes();
        clientes.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadastroFornecedor fornecedor = new CadastroFornecedor();
        fornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListFornecedor fornecedor = new ListFornecedor();
        fornecedor.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItemListarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarEstoqueActionPerformed
        ListEstoque estoque = new ListEstoque();
        estoque.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemListarEstoqueActionPerformed

    private void menuItemRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioVendaActionPerformed
        ListVendas vendas = new ListVendas();
        vendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemRelatorioVendaActionPerformed

    private void menuItemRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRealizarVendaActionPerformed
        /*cadastroVendas venda = new cadastroVendas();
        venda.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_menuItemRealizarVendaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ((ClienteTableModel) tableListarCliente.getModel()).refresh();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListClientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonEditCliente;
    private javax.swing.JButton jButtonRemoveCliente;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBuscaNome;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JLabel labelTituloBusca;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuItemCadastroCliente;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListarEstoque;
    private javax.swing.JMenuItem menuItemRealizarVenda;
    private javax.swing.JMenuItem menuItemRelatorioVenda;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JTable tableListarCliente;
    private javax.swing.JTextField textFieldBuscaNome;
    // End of variables declaration//GEN-END:variables
}
