/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import ClassesDAO.CarneDAO;
import Controle.ControlCarne;
import d.espetos.Carne;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author faad2
 */
public class ListEstoque extends javax.swing.JFrame {

    /**
     * Creates new form listClientes
     */
    Carne[] vCarne;
    private int linhaSelecionada;
    public ListEstoque() {
        initComponents();
        this.setLocationRelativeTo(null);
        vCarne = ControlCarne.getListOfCarneAsArray();
        tableListarCarne.getColumnModel().getColumn(0).setPreferredWidth(30);
        tableListarCarne.getColumnModel().getColumn(3).setPreferredWidth(40);
        tableListarCarne.getColumnModel().getColumn(2).setPreferredWidth(40);
        ((CarneTableModel) tableListarCarne.getModel()).refresh();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        labelTituloBusca = new javax.swing.JLabel();
        jScrollPaneClientes = new javax.swing.JScrollPane();
        tableListarCarne = new javax.swing.JTable();
        textFieldBuscaNome = new javax.swing.JTextField();
        jLabelBuscaNome = new javax.swing.JLabel();
        jButtonBuscarCliente = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuItemCadastroCliente = new javax.swing.JMenuItem();
        menuItemListarClientes = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuItemListarEstoque = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuItemRelatorioVenda = new javax.swing.JMenuItem();
        menuItemRealizarVenda = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setPreferredSize(new java.awt.Dimension(830, 520));
        jPanel1.setLayout(null);

        labelTituloBusca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelTituloBusca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTituloBusca.setText("ESTOQUE");
        jPanel1.add(labelTituloBusca);
        labelTituloBusca.setBounds(300, 0, 110, 20);

        tableListarCarne.setModel(new CarneTableModel(Controle.ControlCarne.getListOfCarne()));
        tableListarCarne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListarCarneMouseClicked(evt);
            }
        });
        jScrollPaneClientes.setViewportView(tableListarCarne);

        jPanel1.add(jScrollPaneClientes);
        jScrollPaneClientes.setBounds(20, 70, 700, 290);
        jPanel1.add(textFieldBuscaNome);
        textFieldBuscaNome.setBounds(120, 30, 390, 22);

        jLabelBuscaNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelBuscaNome.setText("Buscar por Nome ");
        jPanel1.add(jLabelBuscaNome);
        jLabelBuscaNome.setBounds(20, 30, 100, 15);

        jButtonBuscarCliente.setText("Buscar");
        jPanel1.add(jButtonBuscarCliente);
        jButtonBuscarCliente.setBounds(520, 30, 90, 25);

        jButton1.setText("Editar Preço");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(280, 380, 160, 40);

        jButton2.setText("Adicionar Carne");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(80, 380, 160, 40);

        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(470, 380, 160, 40);

        jButton4.setText("Atualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(623, 30, 90, 25);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 20, 740, 440);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoTodos.jpg"))); // NOI18N
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(-20, -20, 830, 520);

        menuPrincipal.setText("Menu Principal");
        menuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPrincipalActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Menu Principal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuPrincipal.add(jMenuItem3);

        barraMenu.add(menuPrincipal);

        menuClientes.setText("Clientes");

        menuItemCadastroCliente.setText("Cadastrar Cliente");
        menuItemCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCadastroClienteActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemCadastroCliente);

        menuItemListarClientes.setText("Listar Clientes");
        menuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemListarClientes);

        barraMenu.add(menuClientes);

        jMenuFornecedores.setText("Fornecedores");

        jMenuItem1.setText("Cadastrar Fornecedor");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuItem1);

        jMenuItem2.setText("Listar Fornecedores");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenuFornecedores.add(jMenuItem2);

        barraMenu.add(jMenuFornecedores);

        menuEstoque.setText("Estoque");

        menuItemListarEstoque.setText("Listar Carnes");
        menuItemListarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemListarEstoque);

        barraMenu.add(menuEstoque);

        menuVendas.setText("Vendas");

        menuItemRelatorioVenda.setText("Relatório de Vendas");
        menuItemRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuItemRelatorioVenda);

        menuItemRealizarVenda.setText("Realizar Venda");
        menuItemRealizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRealizarVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuItemRealizarVenda);

        barraMenu.add(menuVendas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        barraMenu.add(jMenuSair);

        setJMenuBar(barraMenu);

        setBounds(0, 0, 806, 512);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        linhaSelecionada = tableListarCarne.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Selecione uma carne!");
        }
        else{
            Carne carne = new Carne();
            carne.setCodTipo((Integer) tableListarCarne.getValueAt(linhaSelecionada, 7));
            carne.setMarca(tableListarCarne.getValueAt(linhaSelecionada, 6).toString());
            carne.setNomeCarne(tableListarCarne.getValueAt(linhaSelecionada, 1).toString());
            carne.setValorCusto(Double.parseDouble(tableListarCarne.getValueAt(linhaSelecionada, 3).toString()));
            carne.setTipo(tableListarCarne.getValueAt(linhaSelecionada, 8).toString());
            EditarPrecoCarneDialog editCarne = new EditarPrecoCarneDialog(carne, this, true);
            editCarne.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CadCarneDialog cadCarne = new CadCarneDialog(this, true);
        cadCarne.setVisible(true);
        ((CarneTableModel) tableListarCarne.getModel()).refresh();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int linhaSelecionada = tableListarCarne.getSelectedRow();
        if(linhaSelecionada == -1){
            JOptionPane.showMessageDialog(null, "Escolha uma carne!");
        }
        else{
            Carne carne = new Carne((Integer)tableListarCarne.getValueAt(linhaSelecionada,0), (Integer)tableListarCarne.getValueAt(linhaSelecionada, 6));
            CarneDAO.getInstance().delete(carne);
            ((CarneTableModel) tableListarCarne.getModel()).refresh();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableListarCarneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListarCarneMouseClicked
        int linha = tableListarCarne.getSelectedRow();
        Carne c = (Carne) ((CarneTableModel) tableListarCarne.getModel()).getItem(linha);
    }//GEN-LAST:event_tableListarCarneMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        ((CarneTableModel) tableListarCarne.getModel()).refresh();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MenuInicial principal = new MenuInicial();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPrincipalActionPerformed
        MenuInicial principal = new MenuInicial();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuPrincipalActionPerformed

    private void menuItemCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCadastroClienteActionPerformed
        CadClienteDialog clientes = new CadClienteDialog(this, true);
        clientes.setVisible(true);
    }//GEN-LAST:event_menuItemCadastroClienteActionPerformed

    private void menuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarClientesActionPerformed
        ListClientes cliente = new ListClientes();
        cliente.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemListarClientesActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CadFornecedorDialog fornecedor = new CadFornecedorDialog(this, true);
        fornecedor.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        ListFornecedor fornecedor = new ListFornecedor();
        fornecedor.setVisible(true);
        dispose();

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void menuItemListarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarEstoqueActionPerformed
        ListEstoque estoque = new ListEstoque();
        estoque.setVisible(true);
        dispose();
    }//GEN-LAST:event_menuItemListarEstoqueActionPerformed

    private void menuItemRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioVendaActionPerformed
        ListVenda vendas = new ListVenda();
        vendas.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuItemRelatorioVendaActionPerformed

    private void menuItemRealizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRealizarVendaActionPerformed
        /*// TODO add your handling code here:
        cadastroVendas venda = new cadastroVendas();
        venda.setVisible(true);
        dispose();*/
    }//GEN-LAST:event_menuItemRealizarVendaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonBuscarCliente;
    private javax.swing.JLabel jLabelBackground;
    private javax.swing.JLabel jLabelBuscaNome;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPaneClientes;
    private javax.swing.JLabel labelTituloBusca;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuItemCadastroCliente;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListarEstoque;
    private javax.swing.JMenuItem menuItemRealizarVenda;
    private javax.swing.JMenuItem menuItemRelatorioVenda;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuVendas;
    private javax.swing.JTable tableListarCarne;
    private javax.swing.JTextField textFieldBuscaNome;
    // End of variables declaration//GEN-END:variables
}
