/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author faad2
 */
public class MenuEstoque extends javax.swing.JFrame {

    /**
     * Creates new form MenuCarnes
     */
    public MenuEstoque() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAdicionarCarnes = new javax.swing.JButton();
        buttonListarEstoque = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        menuItemCadastroCliente = new javax.swing.JMenuItem();
        menuItemListarClientes = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuItemListarEstoque = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuItemRelatorioVenda = new javax.swing.JMenuItem();
        menuItemRealizarVenda = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 370));
        setResizable(false);
        getContentPane().setLayout(null);

        buttonAdicionarCarnes.setText("Adicionar Carne ao Estoque");
        buttonAdicionarCarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdicionarCarnesActionPerformed(evt);
            }
        });
        getContentPane().add(buttonAdicionarCarnes);
        buttonAdicionarCarnes.setBounds(70, 100, 170, 90);

        buttonListarEstoque.setText("Listar Estoque");
        getContentPane().add(buttonListarEstoque);
        buttonListarEstoque.setBounds(310, 100, 180, 90);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoTodos.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-50, -20, 630, 410);

        menuPrincipal.setText("Menu Principal");

        jMenuItem3.setText("Menu Principal");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        menuPrincipal.add(jMenuItem3);

        barraMenu.add(menuPrincipal);

        menuClientes.setText("Clientes");

        menuItemCadastroCliente.setText("Cadastrar Cliente");
        menuClientes.add(menuItemCadastroCliente);

        menuItemListarClientes.setText("Listar Clientes");
        menuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemListarClientes);

        barraMenu.add(menuClientes);

        jMenuFornecedores.setText("Fornecedores");

        jMenuItem1.setText("Cadastrar Fornecedor");
        jMenuFornecedores.add(jMenuItem1);

        jMenuItem2.setText("Listar Fornecedores");
        jMenuFornecedores.add(jMenuItem2);

        barraMenu.add(jMenuFornecedores);

        menuEstoque.setText("Estoque");

        menuItemListarEstoque.setText("Listar Carnes");
        menuItemListarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemListarEstoque);

        barraMenu.add(menuEstoque);

        menuVendas.setText("Vendas");

        menuItemRelatorioVenda.setText("Relatório de Vendas");
        menuItemRelatorioVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRelatorioVendaActionPerformed(evt);
            }
        });
        menuVendas.add(menuItemRelatorioVenda);

        menuItemRealizarVenda.setText("Realizar Venda");
        menuVendas.add(menuItemRealizarVenda);

        barraMenu.add(menuVendas);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        barraMenu.add(jMenuSair);

        setJMenuBar(barraMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        menuInicial principal = new menuInicial();
        principal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void menuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListarClientesActionPerformed

    private void menuItemListarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListarEstoqueActionPerformed

    private void menuItemRelatorioVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRelatorioVendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemRelatorioVendaActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void buttonAdicionarCarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdicionarCarnesActionPerformed
        CadastrarCarne cadCarne = new CadastrarCarne();
        cadCarne.setVisible(true);
    }//GEN-LAST:event_buttonAdicionarCarnesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuEstoque().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton buttonAdicionarCarnes;
    private javax.swing.JButton buttonListarEstoque;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuItemCadastroCliente;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListarEstoque;
    private javax.swing.JMenuItem menuItemRealizarVenda;
    private javax.swing.JMenuItem menuItemRelatorioVenda;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuVendas;
    // End of variables declaration//GEN-END:variables
}
