/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

/**
 *
 * @author faad2
 */
public class menuCliente extends javax.swing.JFrame {

    /**
     * Creates new form menuCliente
     */
    public menuCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadCliente = new javax.swing.JButton();
        jButtonListCliente = new javax.swing.JButton();
        jButtonExcCliente = new javax.swing.JButton();
        jLabelFundo = new javax.swing.JLabel();
        barraMenu = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenu();
        menuItemCadastroCliente = new javax.swing.JMenuItem();
        menuItemListarClientes = new javax.swing.JMenuItem();
        jMenuFornecedores = new javax.swing.JMenu();
        jMenuItemCadFornecedor = new javax.swing.JMenuItem();
        jMenuItemListFornecedor = new javax.swing.JMenuItem();
        menuEstoque = new javax.swing.JMenu();
        menuItemListarEstoque = new javax.swing.JMenuItem();
        menuVendas = new javax.swing.JMenu();
        menuItemRelatorioVenda = new javax.swing.JMenuItem();
        menuItemRealizarVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jButtonCadCliente.setText("Cadastrar Cliente");
        jButtonCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadCliente);
        jButtonCadCliente.setBounds(50, 130, 150, 98);

        jButtonListCliente.setText("Listar Clientes");
        jButtonListCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonListCliente);
        jButtonListCliente.setBounds(400, 130, 155, 98);

        jButtonExcCliente.setText("Excluir Cliente");
        jButtonExcCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcClienteActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExcCliente);
        jButtonExcCliente.setBounds(220, 130, 160, 100);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fundoTodos.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(-26, -36, 680, 420);

        menuPrincipal.setText("Menu Principal");
        barraMenu.add(menuPrincipal);

        menuClientes.setText("Clientes");

        menuItemCadastroCliente.setText("Cadastrar Cliente");
        menuClientes.add(menuItemCadastroCliente);

        menuItemListarClientes.setText("Listar Clientes");
        menuItemListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarClientesActionPerformed(evt);
            }
        });
        menuClientes.add(menuItemListarClientes);

        barraMenu.add(menuClientes);

        jMenuFornecedores.setText("Fornecedores");

        jMenuItemCadFornecedor.setText("Cadastrar Fornecedor");
        jMenuFornecedores.add(jMenuItemCadFornecedor);

        jMenuItemListFornecedor.setText("Listar Fornecedores");
        jMenuFornecedores.add(jMenuItemListFornecedor);

        barraMenu.add(jMenuFornecedores);

        menuEstoque.setText("Estoque");

        menuItemListarEstoque.setText("Listar Carnes");
        menuItemListarEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemListarEstoqueActionPerformed(evt);
            }
        });
        menuEstoque.add(menuItemListarEstoque);

        barraMenu.add(menuEstoque);

        menuVendas.setText("Vendas");

        menuItemRelatorioVenda.setText("Relatório de Vendas");
        menuVendas.add(menuItemRelatorioVenda);

        menuItemRealizarVenda.setText("Realizar Venda");
        menuVendas.add(menuItemRealizarVenda);

        barraMenu.add(menuVendas);

        setJMenuBar(barraMenu);

        setBounds(0, 0, 629, 411);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadClienteActionPerformed
        // TODO add your handling code here:
        cadastroClientes cadCliente = new cadastroClientes();
        cadCliente.setVisible(true);
    }//GEN-LAST:event_jButtonCadClienteActionPerformed

    private void jButtonListClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListClienteActionPerformed
        // TODO add your handling code here:
        listClientes listCliente = new listClientes();
        listCliente.setVisible(true);
    }//GEN-LAST:event_jButtonListClienteActionPerformed

    private void menuItemListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListarClientesActionPerformed

    private void menuItemListarEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemListarEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuItemListarEstoqueActionPerformed

    private void jButtonExcClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    private javax.swing.JButton jButtonCadCliente;
    private javax.swing.JButton jButtonExcCliente;
    private javax.swing.JButton jButtonListCliente;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JMenu jMenuFornecedores;
    private javax.swing.JMenuItem jMenuItemCadFornecedor;
    private javax.swing.JMenuItem jMenuItemListFornecedor;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuEstoque;
    private javax.swing.JMenuItem menuItemCadastroCliente;
    private javax.swing.JMenuItem menuItemListarClientes;
    private javax.swing.JMenuItem menuItemListarEstoque;
    private javax.swing.JMenuItem menuItemRealizarVenda;
    private javax.swing.JMenuItem menuItemRelatorioVenda;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuVendas;
    // End of variables declaration//GEN-END:variables
}
