/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author faad2
 */
public class verificarSerial extends javax.swing.JFrame {

    /**
     * Creates new form verificarSerial
     */
    public verificarSerial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVerificarLicenca = new javax.swing.JButton();
        txtValidacao = new javax.swing.JTextField();
        txtIdentificador = new javax.swing.JLabel();
        imgFundoValidacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botaoVerificarLicenca.setText("Verificar licença");
        botaoVerificarLicenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVerificarLicencaActionPerformed(evt);
            }
        });
        getContentPane().add(botaoVerificarLicenca, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 193, 170, -1));

        txtValidacao.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtValidacao.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtValidacao.setRequestFocusEnabled(false);
        txtValidacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtValidacaoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                txtValidacaoMousePressed(evt);
            }
        });
        txtValidacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValidacaoActionPerformed(evt);
            }
        });
        getContentPane().add(txtValidacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 160, 170, 30));

        txtIdentificador.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtIdentificador.setText("Digite Sua licença");
        getContentPane().add(txtIdentificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        imgFundoValidacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/FundoLicença - 1.jpg"))); // NOI18N
        getContentPane().add(imgFundoValidacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtValidacaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidacaoMouseClicked
        
    }//GEN-LAST:event_txtValidacaoMouseClicked

    private void txtValidacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValidacaoActionPerformed

    }//GEN-LAST:event_txtValidacaoActionPerformed

    private void txtValidacaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtValidacaoMousePressed
        
    }//GEN-LAST:event_txtValidacaoMousePressed

    private void botaoVerificarLicencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVerificarLicencaActionPerformed
        if(txtValidacao.getText().equals("xxxx-xxxx-xxxx")){
            menuInicial principal = new menuInicial();
            principal.setVisible(true);
            dispose();
            try {
                FileWriter arq = new FileWriter("javaX.txt");
                PrintWriter gravarArq = new PrintWriter(arq);
                gravarArq.printf("Código serial utilizado: " + txtValidacao.getText());
                arq.close();
            } catch (IOException ex) {
                Logger.getLogger(verificarSerial.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Código Serial invalido");
            verificarSerial Validacao = new verificarSerial();
            Validacao.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_botaoVerificarLicencaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(verificarSerial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(verificarSerial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(verificarSerial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(verificarSerial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new verificarSerial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVerificarLicenca;
    private javax.swing.JLabel imgFundoValidacao;
    private javax.swing.JLabel txtIdentificador;
    private javax.swing.JTextField txtValidacao;
    // End of variables declaration//GEN-END:variables
}
